[package]
name = "geo"
description = "Geospatial primitives and algorithms"
version = "0.12.0"
authors = ["Corey Farwell <coreyf@rwell.org>"]
license = "MIT/Apache-2.0"
repository = "https://github.com/georust/geo"
documentation = "https://docs.rs/geo/"
readme = "../README.md"
keywords = ["gis", "geo", "geography", "geospatial"]
autobenches = true
edition = "2018"

[badges]
travis-ci = { repository = "georust/geo" }

[dependencies]
num-traits = { version = "0.2", default-features = false }
serde = { version = "1.0", optional = true, features = ["derive"] }
failure = { version = "0.1.8" }
postgis = { version = "0.6", optional = true }
proj = { version = "0.7", optional = true }
geo-types = { path = "../geo-types", default-features = false,  features = ["rstar"] }
snafu = { version = "0.6.8", default-features = false }

[dependencies.rstar]
git = "https://github.com/zendurix/rstar"
rev = "e188160c5d7483f94110ca60ec0ea66cb428bf60"
default-features = false

[features]
default = []
std = [ "failure/std", "geo-types/std" ]
postgis-integration = ["postgis"]
use-proj = ["proj"]
use-serde = ["serde", "geo-types/serde"]

[dev-dependencies]
approx = "0.3.0"
criterion = { version = "0.2" }

[[bench]]
name = "area"
harness = false

[[bench]]
name = "convex_hull"
harness = false

[[bench]]
name = "vincenty_distance"
harness = false

[[bench]]
name = "extremes"
harness = false

[[bench]]
name = "euclidean_distance"
harness = false

[[bench]]
name = "rotate"
harness = false

[[bench]]
name = "simplify"
harness = false

[package.metadata.docs.rs]
features = ["postgis"]
